version: '3.8'
services:
  backend:
    build:
      context: ./smart-bank
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - database

  frontend:
    build:
      context: ./smart-banking-ui
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend

  database:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: smartbank_db
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
